# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'schedule_design.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(401, 527)
        MainWindow.setStatusTip("")
        MainWindow.setWhatsThis("")
        MainWindow.setAccessibleName("")
        MainWindow.setAccessibleDescription("")
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setWindowFilePath("")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setAnimated(True)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 111, 51))
        self.groupBox.setObjectName("groupBox")
        self.comboBox_faculty = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_faculty.setGeometry(QtCore.QRect(10, 20, 91, 22))
        self.comboBox_faculty.setEditable(False)
        self.comboBox_faculty.setMaxVisibleItems(10)
        self.comboBox_faculty.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.comboBox_faculty.setObjectName("comboBox_faculty")
        self.comboBox_faculty.addItem("")
        self.comboBox_faculty.addItem("")
        self.comboBox_faculty.addItem("")
        self.comboBox_faculty.addItem("")
        self.comboBox_faculty.addItem("")
        self.comboBox_faculty.addItem("")
        self.comboBox_faculty.addItem("")
        self.comboBox_faculty.addItem("")
        self.comboBox_faculty.addItem("")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(130, 0, 131, 51))
        self.groupBox_2.setObjectName("groupBox_2")
        self.comboBox_course = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_course.setGeometry(QtCore.QRect(10, 20, 111, 22))
        self.comboBox_course.setObjectName("comboBox_course")
        self.comboBox_course.addItem("")
        self.comboBox_course.addItem("")
        self.comboBox_course.addItem("")
        self.comboBox_course.addItem("")
        self.comboBox_course.addItem("")
        self.comboBox_course.addItem("")
        self.comboBox_course.addItem("")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(270, 0, 121, 51))
        self.groupBox_3.setObjectName("groupBox_3")
        self.comboBox_group = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_group.setGeometry(QtCore.QRect(10, 20, 101, 22))
        self.comboBox_group.setObjectName("comboBox_group")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 50, 381, 51))
        self.groupBox_4.setObjectName("groupBox_4")
        self.radioButton_week = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_week.setGeometry(QtCore.QRect(10, 20, 91, 20))
        self.radioButton_week.setObjectName("radioButton_week")
        self.radioButton_semestr = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_semestr.setGeometry(QtCore.QRect(110, 20, 91, 20))
        self.radioButton_semestr.setObjectName("radioButton_semestr")
        self.radioButton_date = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_date.setGeometry(QtCore.QRect(210, 20, 71, 20))
        self.radioButton_date.setObjectName("radioButton_date")
        self.radioButton_exam = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_exam.setGeometry(QtCore.QRect(290, 20, 81, 20))
        self.radioButton_exam.setObjectName("radioButton_exam")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 100, 101, 51))
        self.groupBox_5.setObjectName("groupBox_5")
        self.comboBox_week = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_week.setGeometry(QtCore.QRect(10, 20, 81, 22))
        self.comboBox_week.setObjectName("comboBox_week")
        self.comboBox_week.addItem("")
        self.comboBox_week.addItem("")
        self.comboBox_week.addItem("")
        self.comboBox_week.addItem("")
        self.comboBox_week.addItem("")
        self.comboBox_week.addItem("")
        self.comboBox_week.addItem("")
        self.comboBox_week.addItem("")
        self.comboBox_week.addItem("")
        self.comboBox_week.addItem("")
        self.comboBox_week.addItem("")
        self.comboBox_week.addItem("")
        self.comboBox_week.addItem("")
        self.comboBox_week.addItem("")
        self.comboBox_week.addItem("")
        self.comboBox_week.addItem("")
        self.comboBox_week.addItem("")
        self.comboBox_week.addItem("")
        self.comboBox_week.addItem("")
        self.comboBox_week.addItem("")
        self.comboBox_week.addItem("")
        self.comboBox_week.addItem("")
        self.comboBox_week.addItem("")
        self.comboBox_week.addItem("")
        self.comboBox_week.addItem("")
        self.comboBox_week.addItem("")
        self.comboBox_week.addItem("")
        self.comboBox_week.addItem("")
        self.comboBox_week.addItem("")
        self.comboBox_week.addItem("")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(120, 100, 271, 51))
        self.groupBox_6.setObjectName("groupBox_6")
        self.comboBox_semestr = QtWidgets.QComboBox(self.groupBox_6)
        self.comboBox_semestr.setGeometry(QtCore.QRect(10, 20, 251, 22))
        self.comboBox_semestr.setObjectName("comboBox_semestr")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 160, 381, 291))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 460, 381, 41))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.comboBox_faculty.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Расписание УГАТУ"))
        self.groupBox.setTitle(_translate("MainWindow", "Факультет"))
        self.comboBox_faculty.setCurrentText(_translate("MainWindow", "------------"))
        self.comboBox_faculty.setItemText(0, _translate("MainWindow", "------------"))
        self.comboBox_faculty.setItemText(1, _translate("MainWindow", "АВИЭТ"))
        self.comboBox_faculty.setItemText(2, _translate("MainWindow", "ФЗЧС"))
        self.comboBox_faculty.setItemText(3, _translate("MainWindow", "ФАДЭТ"))
        self.comboBox_faculty.setItemText(4, _translate("MainWindow", "УАТ"))
        self.comboBox_faculty.setItemText(5, _translate("MainWindow", "ОНФ"))
        self.comboBox_faculty.setItemText(6, _translate("MainWindow", "ИНЭК"))
        self.comboBox_faculty.setItemText(7, _translate("MainWindow", "ИАТМ"))
        self.comboBox_faculty.setItemText(8, _translate("MainWindow", "ФИРТ"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Курс"))
        self.comboBox_course.setItemText(0, _translate("MainWindow", "------------"))
        self.comboBox_course.setItemText(1, _translate("MainWindow", "Первый курс"))
        self.comboBox_course.setItemText(2, _translate("MainWindow", "Второй курс"))
        self.comboBox_course.setItemText(3, _translate("MainWindow", "Третий курс"))
        self.comboBox_course.setItemText(4, _translate("MainWindow", "Четвертый курс"))
        self.comboBox_course.setItemText(5, _translate("MainWindow", "Пятый курс"))
        self.comboBox_course.setItemText(6, _translate("MainWindow", "Шестой курс"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Группа"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Тип расписания"))
        self.radioButton_week.setText(_translate("MainWindow", "За неделю"))
        self.radioButton_semestr.setText(_translate("MainWindow", "За семестр"))
        self.radioButton_date.setText(_translate("MainWindow", "На дату"))
        self.radioButton_exam.setText(_translate("MainWindow", "Экзамены"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Номер недели"))
        self.comboBox_week.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_week.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_week.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_week.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_week.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_week.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_week.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_week.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_week.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_week.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox_week.setItemText(10, _translate("MainWindow", "12"))
        self.comboBox_week.setItemText(11, _translate("MainWindow", "13"))
        self.comboBox_week.setItemText(12, _translate("MainWindow", "14"))
        self.comboBox_week.setItemText(13, _translate("MainWindow", "15"))
        self.comboBox_week.setItemText(14, _translate("MainWindow", "16"))
        self.comboBox_week.setItemText(15, _translate("MainWindow", "17"))
        self.comboBox_week.setItemText(16, _translate("MainWindow", "18"))
        self.comboBox_week.setItemText(17, _translate("MainWindow", "19"))
        self.comboBox_week.setItemText(18, _translate("MainWindow", "20"))
        self.comboBox_week.setItemText(19, _translate("MainWindow", "21"))
        self.comboBox_week.setItemText(20, _translate("MainWindow", "22"))
        self.comboBox_week.setItemText(21, _translate("MainWindow", "23"))
        self.comboBox_week.setItemText(22, _translate("MainWindow", "24"))
        self.comboBox_week.setItemText(23, _translate("MainWindow", "25"))
        self.comboBox_week.setItemText(24, _translate("MainWindow", "26"))
        self.comboBox_week.setItemText(25, _translate("MainWindow", "27"))
        self.comboBox_week.setItemText(26, _translate("MainWindow", "28"))
        self.comboBox_week.setItemText(27, _translate("MainWindow", "29"))
        self.comboBox_week.setItemText(28, _translate("MainWindow", "30"))
        self.comboBox_week.setItemText(29, _translate("MainWindow", "31"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Семестр"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Показать расписание"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
